using MolkMurders.ViewModels;

namespace MolkMurders.Views;

public partial class GameplayPage : ContentPage
{
	public GameplayPage(GameplayViewModel vm)
	{
		InitializeComponent();
		BindingContext = vm;

		BuildEventBox();
		BuildEventBox();
		BuildEventBox();
		BuildEventBox(); BuildEventBox();

	}

	private void BuildEventBox() {

		Frame frame = new Frame {
			MinimumHeightRequest = 200,
			Content = new VerticalStackLayout {
				Spacing = 10,
				Children = {
					new HorizontalStackLayout {
						HeightRequest = 100, HorizontalOptions = LayoutOptions.Center, Spacing = 15,
						Children = { // HERE is where the pictures are created. One picture = one AbsoluteLayout
							new AbsoluteLayout {
								Children = {
									new Image { // PFP
										Source = "steve.png",
										HeightRequest = 100
									},
									new Image { // ITEM
										Source = "steve.png",
                                        TranslationX = 60, TranslationY = 60,
										HeightRequest = 48
									}
								}
							}
						}
					},
					new HorizontalStackLayout {
						HorizontalOptions = LayoutOptions.Center,
						Children = {
							new Label {
								HorizontalOptions = LayoutOptions.Center, LineBreakMode = LineBreakMode.WordWrap, MaxLines = 3,
								WidthRequest=400,
								Text="It seems that this text was generated by a magical force."
							}
						}
					}
				}
			}
		};

		eventsList.Add(frame);
	}
}